[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

; 强制使用兼容性最好的 DIO 模式
board_build.flash_mode = dio
; 暂时注释掉 2MB 限制，先用默认 4MB 跑通再说
; board_upload.flash_size = 2MB
; board_build.partitions = min_spiffs.csv

build_flags =
  -std=gnu++17
  -D DBG_PRINT_DISABLE=1
  -include Arduino.h
  -I./include
  -I./lib/peripherals/src
  -I./lib/Kinematics/src
  -I./lib/Motion/src
  -I./lib/CamSerial/src

  -I./include/motion_states
  
build_unflags = -std=gnu++11
lib_deps = 
    teckel12/NewPing@^1.9.7
    electroniccats/MPU6050@^1.4.4
    mprograms/QMC5883LCompass@^1.2.3
    adafruit/Adafruit PWM Servo Driver Library @ 2.4.0
    bmellink/IBusBM@^1.1.4

monitor_speed = 115200
monitor_filters = esp32_exception_decoder